spring.application.name=ftn-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ftn-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

server.port=8083

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.servlet.context-path=/ftn
# JWT configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
