package tn.federation.backend.entities;

public enum PressType {
    ARTICLE, VIDEO, PHOTO, COMMUNIQUE,
    COMPETITIONS, RESULTS, OFFICIAL_COMMUNICATIONS, NATIONAL_SELECTIONS, TRAININGS, FEDERAL_EVENTS
}
